### ISSUE TITLE
AttributeError: 'Document' object has no attribute 'get_location'

### ISSUE THREAD

**Issue by bitsnaps** [oliver/gedit-file-search#21]
Hi,
I got this error when clicking on `Search files...`:
```
Traceback (most recent call last):
  File ".../.local/share/gedit/plugins/gedit-file-search/file-search/plugin.py", line 141, in on_search_files_activate
    self._openSearchDialog()
  File ".../.local/share/gedit/plugins/gedit-file-search/file-search/plugin.py", line 146, in _openSearchDialog
    self._searchDialog.show(searchText, searchDirectory)
  File ".../.local/share/gedit/plugins/gedit-file-search/file-search/search_dialog.py", line 194, in show
    gFilePath = self._window.get_active_tab().get_document().get_location()
AttributeError: 'Document' object has no attribute 'get_location'
```
Note: I had to create this directory `/.local/share/gedit/plugins/` and grant permissions to the current user.
ubuntu 20.04.

**Comment by SchrodingersCpp** [comment]
[Here](https://github.com/MicahCarrick/gedit-source-code-browser/issues/35#issuecomment-626104890) is the solution that worked for me.
